eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8091
spring:
  application:
    name: lookUpPoints
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/lookuppoints
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    look-up-points-url: http://localhost:8222/api/v1/look-up-points

management:
  tracing:
    sampling:
      probability: 1.0